# Generated by Django 2.1.7 on 2019-04-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.CharField(help_text='Enter the Parking slot id (eg. s_01, s_02, etc.)', max_length=5)),
                ('status', models.BinaryField(help_text='1 for slot available and 0 for not availabel or blocked or reserved', max_length=1)),
            ],
        ),
    ]
