# Generated by Django 2.1.7 on 2019-04-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot_status',
            name='status',
            field=models.CharField(help_text='Y for slot available and N for not availabel or blocked or reserved', max_length=1),
        ),
    ]
